import { resolveLandingTheme, type LandingThemeKey } from "./theme";
import type { AttributionMode, PublicMetricUnit } from "./contracts";
export type PublicLandingMetricDto = { label: string; beforeValue: string; afterValue: string; unit: PublicMetricUnit };
export type PublicLandingResultDto = { headline: string; narrative: string | null; testimonial: string | null; attributionMode: AttributionMode; attributionLabel: string; metrics: PublicLandingMetricDto[] };
export type PublicCoachLandingDto = { themeKey: LandingThemeKey; coachDisplayName: string; hero: { eyebrow: string | null; headline: string; subheadline: string }; valueProposition: string | null; services: Array<{ title: string; description: string }>; methodology: Array<{ title: string; description: string }>; about: { heading: string | null; body: string | null }; faqs: Array<{ question: string; answer: string }>; cta: { heading: string; body: string | null; whatsappUrl: string; publicEmail: string | null; instagramUrl: string | null }; results: PublicLandingResultDto[]; seo: { title: string; description: string } };
type Source = Record<string, unknown>;
export function toPublicCoachLandingDto(source: Source): PublicCoachLandingDto {
  const results = Array.isArray(source.results) ? source.results.map((result) => { const r = result as Source; return { headline: String(r.headline ?? ""), narrative: (r.narrative as string | null) ?? null, testimonial: (r.testimonial as string | null) ?? null, attributionMode: (r.attributionMode as AttributionMode) ?? "ANONYMOUS", attributionLabel: String(r.attributionLabel ?? "Anónimo"), metrics: Array.isArray(r.metrics) ? r.metrics.map((m) => { const metric = m as Source; return { label: String(metric.label), beforeValue: String(metric.beforeValue), afterValue: String(metric.afterValue), unit: metric.unit as PublicMetricUnit }; }) : [] }; }) : [];
  const themeKey = resolveLandingTheme(String(source.themeKey ?? "")).key;
  // The public projection exposes only a same-origin intent; the server resolves the canonical destination at click time.
  const wa = "/go/whatsapp";
  return { themeKey, coachDisplayName: String(source.coachDisplayName ?? ""), hero: { eyebrow: (source.heroEyebrow as string | null) ?? null, headline: String(source.heroHeadline ?? ""), subheadline: String(source.heroSubheadline ?? "") }, valueProposition: (source.valueProposition as string | null) ?? null, services: Array.isArray(source.services) ? source.services.map((i) => ({ title: String((i as Source).title), description: String((i as Source).description) })) : [], methodology: Array.isArray(source.methodology) ? source.methodology.map((i) => ({ title: String((i as Source).title), description: String((i as Source).description) })) : [], about: { heading: (source.aboutHeading as string | null) ?? null, body: (source.aboutBody as string | null) ?? null }, faqs: Array.isArray(source.faqs) ? source.faqs.map((i) => ({ question: String((i as Source).question), answer: String((i as Source).answer) })) : [], cta: { heading: String(source.ctaHeading ?? ""), body: (source.ctaBody as string | null) ?? null, whatsappUrl: wa, publicEmail: (source.publicEmail as string | null) ?? null, instagramUrl: (source.instagramUrl as string | null) ?? null }, results, seo: { title: String(source.seoTitle ?? source.coachDisplayName ?? ""), description: String(source.seoDescription ?? source.heroSubheadline ?? "") } };
}
