ALTER TABLE "PhotoUploadIntent" ADD COLUMN "checksumSha256" TEXT NOT NULL DEFAULT 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=';
ALTER TABLE "PhotoUploadIntent" ALTER COLUMN "checksumSha256" DROP DEFAULT;
ALTER TABLE "ProgressPhoto" ADD COLUMN "checksumSha256" TEXT NOT NULL DEFAULT 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=';
ALTER TABLE "ProgressPhoto" ALTER COLUMN "checksumSha256" DROP DEFAULT;
